"""
AnalyzaX — Phase 25 Test Suite: AI Copilot & Agentic Workflows.
Validates multi-step workflow planning, human approval gates on consequential mutations,
dashboard plan generation without arbitrary code, context bounding, and memory isolation.
"""

import pytest

from backend.app.engines.ai_copilot.context import ContextEngine
from backend.app.engines.ai_copilot.dashboard_builder import DashboardBuilderEngine
from backend.app.engines.ai_copilot.memory import AnalyticalMemoryEngine
from backend.app.engines.ai_copilot.models import (
    CopilotContext,
    RiskLevel,
    WorkflowStatus,
)
from backend.app.engines.ai_copilot.workflows import WorkflowEngine
from backend.app.engines.semantic.models import MetricDefinition


class TestWorkflowEngineApprovalBoundaries:
    def test_workflow_planning_and_approval_gate(self):
        wf = WorkflowEngine.plan_workflow(
            goal="Clean dataset duplicates and investigate variance",
            user_id="user_1",
            workspace_id="ws_1",
            dataset_id="ds_1",
            version_id="v1",
        )
        assert len(wf.steps) >= 3
        # Look for the mutating step
        mutating_steps = [s for s in wf.steps if s.requires_confirmation]
        assert len(mutating_steps) >= 1
        assert mutating_steps[0].risk_level in (RiskLevel.REVERSIBLE_MUTATION, RiskLevel.CONSEQUENTIAL_MUTATION)

    @pytest.mark.asyncio
    async def test_workflow_execution_pauses_at_approval_gate(self):
        wf = WorkflowEngine.plan_workflow(
            goal="Clean and explore",
            user_id="user_1",
            workspace_id="ws_1",
            dataset_id="ds_1",
            version_id="v1",
        )
        executed_wf = await WorkflowEngine.execute_workflow(wf)
        # Should pause at the mutating step
        assert executed_wf.status == WorkflowStatus.WAITING_FOR_APPROVAL
        waiting_step = executed_wf.steps[executed_wf.current_step_index]
        assert waiting_step.requires_confirmation is True

        # Now resume with explicit user approval
        resumed_wf = await WorkflowEngine.execute_workflow(
            executed_wf,
            approved_step_id=waiting_step.step_id,
        )
        assert resumed_wf.status == WorkflowStatus.COMPLETED


class TestDashboardBuilderEngine:
    def test_dashboard_plan_structure(self):
        metrics = [
            MetricDefinition(
                metric_id="m1",
                workspace_id="ws_1",
                name="Net Sales",
                expression="SUM(sales)",
                owner_id="u1",
            )
        ]
        profile = {
            "columns": {
                "sales": {"inferred_type": "float"},
                "order_date": {"inferred_type": "datetime"},
                "region": {"inferred_type": "string"},
            }
        }
        plan = DashboardBuilderEngine.plan_dashboard(
            title="Sales Performance Overview",
            description="Generated by AI Copilot",
            dataset_id="ds_1",
            version_id="v1",
            profile_data=profile,
            governed_metrics=metrics,
        )
        assert plan.title == "Sales Performance Overview"
        assert len(plan.components) >= 2
        # Check KPI card
        kpis = [c for c in plan.components if c.component_type == "kpi"]
        assert len(kpis) >= 1
        assert kpis[0].title == "Net Sales"
        # Check Chart
        charts = [c for c in plan.components if c.component_type == "chart"]
        assert len(charts) >= 1
        # No arbitrary frontend code, clean ChartSpec
        assert "chart_type" in charts[0].chart_spec


class TestContextAndMemoryEngine:
    def test_bounded_context_construction(self):
        context = CopilotContext(
            workspace_id="ws_1",
            dataset_id="ds_1",
            selected_columns=["revenue", "cost"],
        )
        profile_sample = {f"col_{i}": {"inferred_type": "integer"} for i in range(100)}
        assembled = ContextEngine.build_context(context, profile_data={"columns": profile_sample})
        # Verifies token and column budgeting
        assert len(assembled["columns"]) <= 30

    def test_scoped_analytical_memory_sanitization(self):
        mem_engine = AnalyticalMemoryEngine()
        mem_engine.record_memory(
            scope="SESSION",
            scope_id="sess_1",
            key="user_query",
            content={"message": "Here is my key: sk-ant-api03-secret123456789 and my email test@example.com"},
        )
        recent = mem_engine.get_recent_context(scope="SESSION", scope_id="sess_1")
        assert len(recent) == 1
        stored_str = str(recent[0].content)
        # Secret should be redacted
        assert "sk-ant-api03" not in stored_str
        assert "[REDACTED_SECRET]" in stored_str
