/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAnalystRouteImport } from './routes/ai-analyst'
import { Route as CleaningRouteImport } from './routes/cleaning'
import { Route as DataRouteImport } from './routes/data'
import { Route as EdaRouteImport } from './routes/eda'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as MlRouteImport } from './routes/ml'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as TeamRouteImport } from './routes/team'
import { Route as VisualizationsRouteImport } from './routes/visualizations'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalystRoute = AiAnalystRouteImport.update({
  id: '/ai-analyst',
  path: '/ai-analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningRoute = CleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const EdaRoute = EdaRouteImport.update({
  id: '/eda',
  path: '/eda',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MlRoute = MlRouteImport.update({
  id: '/ml',
  path: '/ml',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationsRoute = VisualizationsRouteImport.update({
  id: '/visualizations',
  path: '/visualizations',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analyst': typeof AiAnalystRoute
  '/cleaning': typeof CleaningRoute
  '/data': typeof DataRoute
  '/eda': typeof EdaRoute
  '/exports': typeof ExportsRoute
  '/forecasting': typeof ForecastingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/ml': typeof MlRoute
  '/notifications': typeof NotificationsRoute
  '/quality': typeof QualityRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql': typeof SqlRoute
  '/statistics': typeof StatisticsRoute
  '/team': typeof TeamRoute
  '/visualizations': typeof VisualizationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analyst': typeof AiAnalystRoute
  '/cleaning': typeof CleaningRoute
  '/data': typeof DataRoute
  '/eda': typeof EdaRoute
  '/exports': typeof ExportsRoute
  '/forecasting': typeof ForecastingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/ml': typeof MlRoute
  '/notifications': typeof NotificationsRoute
  '/quality': typeof QualityRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql': typeof SqlRoute
  '/statistics': typeof StatisticsRoute
  '/team': typeof TeamRoute
  '/visualizations': typeof VisualizationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analyst': typeof AiAnalystRoute
  '/cleaning': typeof CleaningRoute
  '/data': typeof DataRoute
  '/eda': typeof EdaRoute
  '/exports': typeof ExportsRoute
  '/forecasting': typeof ForecastingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/ml': typeof MlRoute
  '/notifications': typeof NotificationsRoute
  '/quality': typeof QualityRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sql': typeof SqlRoute
  '/statistics': typeof StatisticsRoute
  '/team': typeof TeamRoute
  '/visualizations': typeof VisualizationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analyst'
    | '/cleaning'
    | '/data'
    | '/eda'
    | '/exports'
    | '/forecasting'
    | '/forgot-password'
    | '/insights'
    | '/login'
    | '/metrics'
    | '/ml'
    | '/notifications'
    | '/quality'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/sql'
    | '/statistics'
    | '/team'
    | '/visualizations'
    | '/invite/$token'
    | '/projects/$id'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analyst'
    | '/cleaning'
    | '/data'
    | '/eda'
    | '/exports'
    | '/forecasting'
    | '/forgot-password'
    | '/insights'
    | '/login'
    | '/metrics'
    | '/ml'
    | '/notifications'
    | '/quality'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/sql'
    | '/statistics'
    | '/team'
    | '/visualizations'
    | '/invite/$token'
    | '/projects/$id'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/ai-analyst'
    | '/cleaning'
    | '/data'
    | '/eda'
    | '/exports'
    | '/forecasting'
    | '/forgot-password'
    | '/insights'
    | '/login'
    | '/metrics'
    | '/ml'
    | '/notifications'
    | '/quality'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/sql'
    | '/statistics'
    | '/team'
    | '/visualizations'
    | '/invite/$token'
    | '/projects/$id'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalystRoute: typeof AiAnalystRoute
  CleaningRoute: typeof CleaningRoute
  DataRoute: typeof DataRoute
  EdaRoute: typeof EdaRoute
  ExportsRoute: typeof ExportsRoute
  ForecastingRoute: typeof ForecastingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  MetricsRoute: typeof MetricsRoute
  MlRoute: typeof MlRoute
  NotificationsRoute: typeof NotificationsRoute
  QualityRoute: typeof QualityRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SqlRoute: typeof SqlRoute
  StatisticsRoute: typeof StatisticsRoute
  TeamRoute: typeof TeamRoute
  VisualizationsRoute: typeof VisualizationsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analyst': {
      id: '/ai-analyst'
      path: '/ai-analyst'
      fullPath: '/ai-analyst'
      preLoaderRoute: typeof AiAnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning': {
      id: '/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof CleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eda': {
      id: '/eda'
      path: '/eda'
      fullPath: '/eda'
      preLoaderRoute: typeof EdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml': {
      id: '/ml'
      path: '/ml'
      fullPath: '/ml'
      preLoaderRoute: typeof MlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizations': {
      id: '/visualizations'
      path: '/visualizations'
      fullPath: '/visualizations'
      preLoaderRoute: typeof VisualizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalystRoute: AiAnalystRoute,
  CleaningRoute: CleaningRoute,
  DataRoute: DataRoute,
  EdaRoute: EdaRoute,
  ExportsRoute: ExportsRoute,
  ForecastingRoute: ForecastingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  MetricsRoute: MetricsRoute,
  MlRoute: MlRoute,
  NotificationsRoute: NotificationsRoute,
  QualityRoute: QualityRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SqlRoute: SqlRoute,
  StatisticsRoute: StatisticsRoute,
  TeamRoute: TeamRoute,
  VisualizationsRoute: VisualizationsRoute,
  InviteTokenRoute: InviteTokenRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
